project:
  type: website
  output-dir: ./_site

website:
  title: "Attclimate - Projecte de recerca"
  navbar:
    left:
      - href: index.qmd
        text: Inici
      - href: about.qmd
        text: Sobre
      - href: team.qmd
        text: Equip
      - href: research.qmd
        text: Recerca
      - href: data.qmd
        text: Codi
    right:
      - href: /index.html
        text: Català
      - href: ./en/index_en.html
        text: English

lang: ca

format:
  html:
    theme: darkly
    css: styles.css
    toc: true
    toc-depth: 2
    link-external-icon: true
    link-external-newwindow: true

editor: visual