project:
  type: website
  output-dir: ./_site
  render:
    - "*.qmd"
    - "!map.qmd"
  resources:
    - CNAME

website:
  title: "ATTClimate / ATTClimpols"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: data_en.qmd
        text: Attclimate dataset
      - href: https://mguinjoan.shinyapps.io/attclimate/
        text: Panel data analysis
      - href: papers.qmd
        text: Papers
      - href: team_en.qmd
        text: Team

lang: en

format:
  html:
    theme:
      dark: darkly
      light: flatly
    css: styles.css
    toc: true
    toc-depth: 2
    link-external-icon: true
    link-external-newwindow: true
    include-after-body: _navbar-newtab.html

editor: visual
