project:
  type: website
  output-dir: ./_site/en


website:
  title: "Attclimate research project"
  navbar:
    left:
      - href: index_en.qmd
        text: Home
      - href: about_en.qmd
        text: About
      - href: team_en.qmd
        text: Team
      - href: research_en.qmd
        text: Research
      - href: data_en.qmd
        text: Code
      - href: map.qmd
        text: Map
    right:
      - href: ../index.html
        text: Català
      - href: ./index_en.html
        text: English

lang: en

format:
  html:
    theme: darkly
    css: styles.css
    toc: true
    toc-depth: 2
    link-external-icon: true
    link-external-newwindow: true

editor: visual
