---
title: "Team"
---

::: {style="text-align: justify"}
The project is led by professors **Marc Guinjoan** and **Toni Rodon**, and includes a team of data analysts, research assistants, and doctoral students.

[**Jordi Mas (UOC)**](https://www.jordimas.cat/) is a co-principal investigator of the project. Mas is a lecturer at the Faculty of Law and Political Science at the Universitat Oberta de Catalunya. This research interests include the fields of data governance, political economy and political institutions.

[**Toni Rodon (UPF)**](https://tonirodon.cat/ca/) is a co-principal investigator of the project. Rodon is an Associate Professor at the Department of Political and Social Sciences at Universitat Pompeu Fabra, and a researcher at the London School of Economics and Political Science (United Kingdom). His research interests include political behavior, public opinion, historical political economy, and political geography, among others.

[**Marc Guinjoan (UOC)**](https://sites.google.com/site/marcguinjoan) is a researcher in the project. He is a lecturer in the Department of Political Science and Public Law at the Universitat Autònoma de Barcelona. His main research areas include political and electoral behavior, political parties, electoral systems, populism, and political psychology. He has also worked extensively on decentralization processes, identities, and territorial preferences.

[**Roger Sanjaume**](https://rogersanjaume.cat/) is a data analyst programmer. He currently works as a data engineer in an electric sector cooperative. He has collaborated with research projects such as the Institutions and Political Economy Research Group (IPErG) as a data analyst. He is the editor of the postgraduate manual "Data Analyst for Political Analysis and Public Management" at the University of Barcelona.

**Cèlia Estruch** is a research assistant. She has completed the "Master in Political Science and Political Economy" at the London School of Economics and Political Science (United Kingdom). She has also completed the postgraduate program "Data Analyst for Political Analysis and Public Management" at the University of Barcelona and the Degree in Philosophy, Politics, and Economics at Universitat Pompeu Fabra.

**Joel Ardiaca** is a research assistant. He currently works as a statistician at the Centre for Opinion Studies and is pursuing a master's degree in Statistics and Operations Research at the Polytechnic University of Catalonia. He has completed a double degree in Statistics and Sociology at the Universitat Autònoma de Barcelona.

[**Elena Romanin**](https://elenaromanin.github.io/index.html) is a doctoral student in Political and Social Sciences at Universitat Pompeu Fabra. She has previously been a researcher at the Research and Expertise Centre for Survey Methodology (UPF), where she collaborated on the research project [ICOS Cities Pilot Applications in Urban Landscapes - Towards integrated city Observatories for greenhouse gases (PAUL)](https://www.icos-cp.eu/about/icos-in-nutshell/mission). She has completed the Master in Economics and Development at the University of Florence, and the Degree in International Studies at the University of Trento.

Also part of the project team are **Joaquín Rozas**, **Emmanuele Murgolo**, and **Nikandros Ioannidis**, doctoral students at Pompeu Fabra University.
:::
