on:
  workflow_dispatch:
  push:
    branches: main

name: Quarto Publish

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Set up Quarto
        uses: quarto-dev/quarto-actions/setup@v2

      - name: Install R
        uses: r-lib/actions/setup-r@v2
        with:
          r-version: '4.2.0'

      - name: Install R Dependencies
        uses: r-lib/actions/setup-renv@v2
        with:
          cache-version: 1

      - name: 'Render'
        env:
          QUARTO_PRINT_STACK: true
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          quarto render --profile catala
          querto render --profile english
          if [ -f "_book" ]; then
            echo "QUARTO_OUTPUT=_book" >> $GITHUB_ENV
          elif [ -f "_site" ]; then
            echo "QUARTO_OUTPUT=_site" >> $GITHUB_ENV
          fi
        shell: bash